import { ICards } from '../src/types/interfaces';

export const cards: ICards[] = [
  {
    category: 'Action (set A)',
    hash: 'category_action-set-a',
    cardsList: [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'api/content/img/cry.jpg',
        audioSrc: 'api/content/audio/cry.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'api/content/img/dance.jpg',
        audioSrc: 'api/content/audio/dance.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'api/content/img/dive.jpg',
        audioSrc: 'api/content/audio/dive.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'api/content/img/draw.jpg',
        audioSrc: 'api/content/audio/draw.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'api/content/img/fish.jpg',
        audioSrc: 'api/content/audio/fish.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'api/content/img/fly.jpg',
        audioSrc: 'api/content/audio/fly.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'api/content/img/hug.jpg',
        audioSrc: 'api/content/audio/hug.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'api/content/img/jump.jpg',
        audioSrc: 'api/content/audio/jump.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Action (set B)',
    hash: 'category_action-set-b',
    cardsList: [
      {
        word: 'open',
        translation: 'открывать',
        image: 'api/content/img/open.jpg',
        audioSrc: 'api/content/audio/open.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'api/content/img/play.jpg',
        audioSrc: 'api/content/audio/play.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'api/content/img/point.jpg',
        audioSrc: 'api/content/audio/point.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'api/content/img/ride.jpg',
        audioSrc: 'api/content/audio/ride.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'api/content/img/run.jpg',
        audioSrc: 'api/content/audio/run.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'api/content/img/sing.jpg',
        audioSrc: 'api/content/audio/sing.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'skip',
        translation: 'пропускать, прыгать',
        image: 'api/content/img/skip.jpg',
        audioSrc: 'api/content/audio/skip.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'api/content/img/swim.jpg',
        audioSrc: 'api/content/audio/swim.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Action (set С)',
    hash: 'category_action-set-c',
    cardsList: [
      {
        word: 'argue',
        translation: 'спорить',
        image: 'api/content/img/argue.jpg',
        audioSrc: 'api/content/audio/argue.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'build',
        translation: 'строить',
        image: 'api/content/img/build.jpg',
        audioSrc: 'api/content/audio/build.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'carry',
        translation: 'нести',
        image: 'api/content/img/carry.jpg',
        audioSrc: 'api/content/audio/carry.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'catch',
        translation: 'ловить',
        image: 'api/content/img/catch.jpg',
        audioSrc: 'api/content/audio/catch.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'drive',
        translation: 'водить машину',
        image: 'api/content/img/drive.jpg',
        audioSrc: 'api/content/audio/drive.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'drop',
        translation: 'падать',
        image: 'api/content/img/drop.jpg',
        audioSrc: 'api/content/audio/drop.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'pull',
        translation: 'тянуть',
        image: 'api/content/img/pull.jpg',
        audioSrc: 'api/content/audio/pull.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'push',
        translation: 'толкать',
        image: 'api/content/img/push.jpg',
        audioSrc: 'api/content/audio/push.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Adjective',
    hash: 'category_adjective',
    cardsList: [
      {
        word: 'big',
        translation: 'большой',
        image: 'api/content/img/big.jpg',
        audioSrc: 'api/content/audio/big.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'small',
        translation: 'маленький',
        image: 'api/content/img/small.jpg',
        audioSrc: 'api/content/audio/small.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'fast',
        translation: 'быстрый',
        image: 'api/content/img/fast.jpg',
        audioSrc: 'api/content/audio/fast.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'slow',
        translation: 'медленный',
        image: 'api/content/img/slow.jpg',
        audioSrc: 'api/content/audio/slow.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'friendly',
        translation: 'дружелюбный',
        image: 'api/content/img/friendly.jpg',
        audioSrc: 'api/content/audio/friendly.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'unfriendly',
        translation: 'недружелюбный',
        image: 'api/content/img/unfriendly.jpg',
        audioSrc: 'api/content/audio/unfriendly.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'young',
        translation: 'молодой',
        image: 'api/content/img/young.jpg',
        audioSrc: 'api/content/audio/young.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'old',
        translation: 'старый',
        image: 'api/content/img/old.jpg',
        audioSrc: 'api/content/audio/old.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Animal (set A)',
    hash: 'category_animal-set-a',
    cardsList: [
      {
        word: 'cat',
        translation: 'кот',
        image: 'api/content/img/cat.jpg',
        audioSrc: 'api/content/audio/cat.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'api/content/img/chick.jpg',
        audioSrc: 'api/content/audio/chick.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'api/content/img/chicken.jpg',
        audioSrc: 'api/content/audio/chicken.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'api/content/img/dog.jpg',
        audioSrc: 'api/content/audio/dog.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'api/content/img/horse.jpg',
        audioSrc: 'api/content/audio/horse.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'api/content/img/pig.jpg',
        audioSrc: 'api/content/audio/pig.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'api/content/img/rabbit.jpg',
        audioSrc: 'api/content/audio/rabbit.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'api/content/img/sheep.jpg',
        audioSrc: 'api/content/audio/sheep.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Animal (set B)',
    hash: 'category_animal-set-b',
    cardsList: [
      {
        word: 'bird',
        translation: 'птица',
        image: 'api/content/img/bird.jpg',
        audioSrc: 'api/content/audio/bird.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'api/content/img/fish1.jpg',
        audioSrc: 'api/content/audio/fish.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'api/content/img/frog.jpg',
        audioSrc: 'api/content/audio/frog.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'api/content/img/giraffe.jpg',
        audioSrc: 'api/content/audio/giraffe.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'api/content/img/lion.jpg',
        audioSrc: 'api/content/audio/lion.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'api/content/img/mouse.jpg',
        audioSrc: 'api/content/audio/mouse.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'api/content/img/turtle.jpg',
        audioSrc: 'api/content/audio/turtle.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'api/content/img/dolphin.jpg',
        audioSrc: 'api/content/audio/dolphin.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Clothes',
    hash: 'category_clothes',
    cardsList: [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'api/content/img/skirt.jpg',
        audioSrc: 'api/content/audio/skirt.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'api/content/img/pants.jpg',
        audioSrc: 'api/content/audio/pants.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'api/content/img/blouse.jpg',
        audioSrc: 'api/content/audio/blouse.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'api/content/img/dress.jpg',
        audioSrc: 'api/content/audio/dress.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'api/content/img/boot.jpg',
        audioSrc: 'api/content/audio/boot.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'api/content/img/shirt.jpg',
        audioSrc: 'api/content/audio/shirt.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'api/content/img/coat.jpg',
        audioSrc: 'api/content/audio/coat.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'api/content/img/shoe.jpg',
        audioSrc: 'api/content/audio/shoe.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
  {
    category: 'Emotions',
    hash: 'category_emotions',
    cardsList: [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'api/content/img/sad.jpg',
        audioSrc: 'api/content/audio/sad.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'api/content/img/angry.jpg',
        audioSrc: 'api/content/audio/angry.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'api/content/img/happy.jpg',
        audioSrc: 'api/content/audio/happy.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'api/content/img/tired.jpg',
        audioSrc: 'api/content/audio/tired.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'api/content/img/surprised.jpg',
        audioSrc: 'api/content/audio/surprised.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'api/content/img/scared.jpg',
        audioSrc: 'api/content/audio/scared.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'api/content/img/smile.jpg',
        audioSrc: 'api/content/audio/smile.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'api/content/img/laugh.jpg',
        audioSrc: 'api/content/audio/laugh.mp3',
        train: 0,
        hit: 0,
        miss: 0,
      },
    ],
  },
];
